/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "protocol.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(protocol_Layer, protocol_Layer, AUTO)


PB_BIND(protocol_Animation, protocol_Animation, AUTO)


PB_BIND(protocol_Sequence, protocol_Sequence, AUTO)


PB_BIND(protocol_Settings, protocol_Settings, AUTO)


PB_BIND(protocol_BroadcastSequence, protocol_BroadcastSequence, AUTO)


PB_BIND(protocol_State, protocol_State, AUTO)


PB_BIND(protocol_Message, protocol_Message, AUTO)


PB_BIND(protocol_Animation2, protocol_Animation2, AUTO)


PB_BIND(protocol_Layer2, protocol_Layer2, AUTO)


PB_BIND(protocol_FadeColor2, protocol_FadeColor2, AUTO)


PB_BIND(protocol_RainbowColor2, protocol_RainbowColor2, AUTO)







