/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_PROTOCOL_PROTOCOL_PB_H_INCLUDED
#define PB_PROTOCOL_PROTOCOL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _protocol_LayerType {
    /* Colors */
    protocol_LayerType_SingleColor = 0,
    protocol_LayerType_RainbowColor = 1,
    protocol_LayerType_SectionsWaveColor = 2,
    protocol_LayerType_SectionsColor = 3,
    protocol_LayerType_FadeColor = 4,
    protocol_LayerType_SwitchColor = 5,
    /* Masks - 50 offset */
    protocol_LayerType_BlinkMask = 50,
    protocol_LayerType_InvertMask = 51,
    protocol_LayerType_PulseSawtoothMask = 52,
    protocol_LayerType_PulseMask = 53,
    protocol_LayerType_SawtoothMask = 54,
    protocol_LayerType_SectionsWaveMask = 55,
    protocol_LayerType_SectionsMask = 56,
    protocol_LayerType_StarsMask = 57,
    protocol_LayerType_WaveMask = 58
} protocol_LayerType;

typedef enum _protocol_Direction {
    protocol_Direction_FORWARD = 0,
    protocol_Direction_BACKWARD = 1
} protocol_Direction;

typedef enum _protocol_MessageType {
    protocol_MessageType_SET_SEQUENCE = 0, /* For live setting the current animation sequence. */
    protocol_MessageType_SAVE_SEQUENCE = 1, /* Save new default sequence to the device. */
    protocol_MessageType_SAVE_SETTINGS = 2, /* Save new settings to the device. */
    protocol_MessageType_REQUEST_STATE = 3, /* Request the current sequence and settings from the device. */
    protocol_MessageType_RESPONSE_STATE = 4 /* Response with the current sequence and settings from the device. */
} protocol_MessageType;

typedef enum _protocol_ForwardingType {
    protocol_ForwardingType_NOCAST = 0, /* Send to a specific device */
    protocol_ForwardingType_BROADCAST = 1, /* Send to all devices */
    protocol_ForwardingType_MULTICAST = 2 /* Send to a group of devices */
} protocol_ForwardingType;

/* Struct definitions */
/* The request message containing the desired effect and brightness. */
typedef struct _protocol_Layer {
    protocol_LayerType type;
    uint32_t duration;
    uint32_t length;
    uint32_t color;
    uint32_t gap;
    uint32_t frequency;
    uint32_t speed;
    pb_callback_t colors;
    pb_callback_t sections;
} protocol_Layer;

/* The request message containing an array of effects. */
typedef struct _protocol_Animation {
    protocol_Direction direction;
    uint32_t duration;
    uint32_t first_tick; /* Which tick should the animation start on. */
    uint32_t brightness;
    pb_callback_t layers;
} protocol_Animation;

typedef struct _protocol_Sequence {
    pb_callback_t animations;
} protocol_Sequence;

typedef struct _protocol_Settings {
    uint32_t group_id; /* Specify the group ID for the DMX controller */
    uint32_t virtual_offset; /* Set virtual index of first led for the DMX controller. */
} protocol_Settings;

typedef struct _protocol_Message {
    protocol_MessageType type;
    bool has_settings;
    protocol_Settings settings; /* Is included if message has to do with settings. */
    bool has_sequence;
    protocol_Sequence sequence; /* Is included if message has to do with sequences. */
    protocol_ForwardingType forwarding_type; /* Which devices should the message be sent to. */
    pb_callback_t target_groups; /* If ForwardingType is Multicast, this is the list of groups to send to. */
} protocol_Message;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _protocol_LayerType_MIN protocol_LayerType_SingleColor
#define _protocol_LayerType_MAX protocol_LayerType_WaveMask
#define _protocol_LayerType_ARRAYSIZE ((protocol_LayerType)(protocol_LayerType_WaveMask+1))

#define _protocol_Direction_MIN protocol_Direction_FORWARD
#define _protocol_Direction_MAX protocol_Direction_BACKWARD
#define _protocol_Direction_ARRAYSIZE ((protocol_Direction)(protocol_Direction_BACKWARD+1))

#define _protocol_MessageType_MIN protocol_MessageType_SET_SEQUENCE
#define _protocol_MessageType_MAX protocol_MessageType_RESPONSE_STATE
#define _protocol_MessageType_ARRAYSIZE ((protocol_MessageType)(protocol_MessageType_RESPONSE_STATE+1))

#define _protocol_ForwardingType_MIN protocol_ForwardingType_NOCAST
#define _protocol_ForwardingType_MAX protocol_ForwardingType_MULTICAST
#define _protocol_ForwardingType_ARRAYSIZE ((protocol_ForwardingType)(protocol_ForwardingType_MULTICAST+1))

#define protocol_Layer_type_ENUMTYPE protocol_LayerType

#define protocol_Animation_direction_ENUMTYPE protocol_Direction



#define protocol_Message_type_ENUMTYPE protocol_MessageType
#define protocol_Message_forwarding_type_ENUMTYPE protocol_ForwardingType


/* Initializer values for message structs */
#define protocol_Layer_init_default              {_protocol_LayerType_MIN, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define protocol_Animation_init_default          {_protocol_Direction_MIN, 0, 0, 0, {{NULL}, NULL}}
#define protocol_Sequence_init_default           {{{NULL}, NULL}}
#define protocol_Settings_init_default           {0, 0}
#define protocol_Message_init_default            {_protocol_MessageType_MIN, false, protocol_Settings_init_default, false, protocol_Sequence_init_default, _protocol_ForwardingType_MIN, {{NULL}, NULL}}
#define protocol_Layer_init_zero                 {_protocol_LayerType_MIN, 0, 0, 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define protocol_Animation_init_zero             {_protocol_Direction_MIN, 0, 0, 0, {{NULL}, NULL}}
#define protocol_Sequence_init_zero              {{{NULL}, NULL}}
#define protocol_Settings_init_zero              {0, 0}
#define protocol_Message_init_zero               {_protocol_MessageType_MIN, false, protocol_Settings_init_zero, false, protocol_Sequence_init_zero, _protocol_ForwardingType_MIN, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define protocol_Layer_type_tag                  1
#define protocol_Layer_duration_tag              2
#define protocol_Layer_length_tag                3
#define protocol_Layer_color_tag                 4
#define protocol_Layer_gap_tag                   5
#define protocol_Layer_frequency_tag             6
#define protocol_Layer_speed_tag                 7
#define protocol_Layer_colors_tag                8
#define protocol_Layer_sections_tag              9
#define protocol_Animation_direction_tag         1
#define protocol_Animation_duration_tag          2
#define protocol_Animation_first_tick_tag        3
#define protocol_Animation_brightness_tag        4
#define protocol_Animation_layers_tag            5
#define protocol_Sequence_animations_tag         2
#define protocol_Settings_group_id_tag           1
#define protocol_Settings_virtual_offset_tag     2
#define protocol_Message_type_tag                1
#define protocol_Message_settings_tag            2
#define protocol_Message_sequence_tag            3
#define protocol_Message_forwarding_type_tag     4
#define protocol_Message_target_groups_tag       5

/* Struct field encoding specification for nanopb */
#define protocol_Layer_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, UINT32,   duration,          2) \
X(a, STATIC,   SINGULAR, UINT32,   length,            3) \
X(a, STATIC,   SINGULAR, UINT32,   color,             4) \
X(a, STATIC,   SINGULAR, UINT32,   gap,               5) \
X(a, STATIC,   SINGULAR, UINT32,   frequency,         6) \
X(a, STATIC,   SINGULAR, UINT32,   speed,             7) \
X(a, CALLBACK, REPEATED, UINT32,   colors,            8) \
X(a, CALLBACK, SINGULAR, BYTES,    sections,          9)
#define protocol_Layer_CALLBACK pb_default_field_callback
#define protocol_Layer_DEFAULT NULL

#define protocol_Animation_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    direction,         1) \
X(a, STATIC,   SINGULAR, UINT32,   duration,          2) \
X(a, STATIC,   SINGULAR, UINT32,   first_tick,        3) \
X(a, STATIC,   SINGULAR, UINT32,   brightness,        4) \
X(a, CALLBACK, REPEATED, MESSAGE,  layers,            5)
#define protocol_Animation_CALLBACK pb_default_field_callback
#define protocol_Animation_DEFAULT NULL
#define protocol_Animation_layers_MSGTYPE protocol_Layer

#define protocol_Sequence_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  animations,        2)
#define protocol_Sequence_CALLBACK pb_default_field_callback
#define protocol_Sequence_DEFAULT NULL
#define protocol_Sequence_animations_MSGTYPE protocol_Animation

#define protocol_Settings_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   group_id,          1) \
X(a, STATIC,   SINGULAR, UINT32,   virtual_offset,    2)
#define protocol_Settings_CALLBACK NULL
#define protocol_Settings_DEFAULT NULL

#define protocol_Message_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  settings,          2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sequence,          3) \
X(a, STATIC,   SINGULAR, UENUM,    forwarding_type,   4) \
X(a, CALLBACK, REPEATED, UINT32,   target_groups,     5)
#define protocol_Message_CALLBACK pb_default_field_callback
#define protocol_Message_DEFAULT NULL
#define protocol_Message_settings_MSGTYPE protocol_Settings
#define protocol_Message_sequence_MSGTYPE protocol_Sequence

extern const pb_msgdesc_t protocol_Layer_msg;
extern const pb_msgdesc_t protocol_Animation_msg;
extern const pb_msgdesc_t protocol_Sequence_msg;
extern const pb_msgdesc_t protocol_Settings_msg;
extern const pb_msgdesc_t protocol_Message_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define protocol_Layer_fields &protocol_Layer_msg
#define protocol_Animation_fields &protocol_Animation_msg
#define protocol_Sequence_fields &protocol_Sequence_msg
#define protocol_Settings_fields &protocol_Settings_msg
#define protocol_Message_fields &protocol_Message_msg

/* Maximum encoded size of messages (where known) */
/* protocol_Layer_size depends on runtime parameters */
/* protocol_Animation_size depends on runtime parameters */
/* protocol_Sequence_size depends on runtime parameters */
/* protocol_Message_size depends on runtime parameters */
#define PROTOCOL_PROTOCOL_PB_H_MAX_SIZE          protocol_Settings_size
#define protocol_Settings_size                   12

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
