/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_LED_PROTOCOLS_SRC_PROTOCOL_PB_H_INCLUDED
#define PB_LED_PROTOCOLS_SRC_PROTOCOL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _led_protocols_Direction {
    led_protocols_Direction_FORWARD = 0,
    led_protocols_Direction_BACKWARD = 1
} led_protocols_Direction;

/* Struct definitions */
/* The request message containing the desired effect and brightness. */
typedef struct _led_protocols_Layer {
    uint32_t effect;
    uint32_t p1;
    uint32_t p2;
    uint32_t p3;
    pb_callback_t effect_set;
} led_protocols_Layer;

/* The request message containing an array of effects. */
typedef struct _led_protocols_Animation {
    led_protocols_Direction direction;
    uint32_t duration;
    pb_callback_t layers;
} led_protocols_Animation;

typedef struct _led_protocols_Sequence {
    uint32_t brightness;
    pb_callback_t animations;
} led_protocols_Sequence;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _led_protocols_Direction_MIN led_protocols_Direction_FORWARD
#define _led_protocols_Direction_MAX led_protocols_Direction_BACKWARD
#define _led_protocols_Direction_ARRAYSIZE ((led_protocols_Direction)(led_protocols_Direction_BACKWARD+1))


#define led_protocols_Animation_direction_ENUMTYPE led_protocols_Direction



/* Initializer values for message structs */
#define led_protocols_Layer_init_default         {0, 0, 0, 0, {{NULL}, NULL}}
#define led_protocols_Animation_init_default     {_led_protocols_Direction_MIN, 0, {{NULL}, NULL}}
#define led_protocols_Sequence_init_default      {0, {{NULL}, NULL}}
#define led_protocols_Layer_init_zero            {0, 0, 0, 0, {{NULL}, NULL}}
#define led_protocols_Animation_init_zero        {_led_protocols_Direction_MIN, 0, {{NULL}, NULL}}
#define led_protocols_Sequence_init_zero         {0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define led_protocols_Layer_effect_tag           1
#define led_protocols_Layer_p1_tag               2
#define led_protocols_Layer_p2_tag               3
#define led_protocols_Layer_p3_tag               4
#define led_protocols_Layer_effect_set_tag       5
#define led_protocols_Animation_direction_tag    1
#define led_protocols_Animation_duration_tag     2
#define led_protocols_Animation_layers_tag       3
#define led_protocols_Sequence_brightness_tag    1
#define led_protocols_Sequence_animations_tag    2

/* Struct field encoding specification for nanopb */
#define led_protocols_Layer_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   effect,            1) \
X(a, STATIC,   SINGULAR, UINT32,   p1,                2) \
X(a, STATIC,   SINGULAR, UINT32,   p2,                3) \
X(a, STATIC,   SINGULAR, UINT32,   p3,                4) \
X(a, CALLBACK, REPEATED, UINT32,   effect_set,        5)
#define led_protocols_Layer_CALLBACK pb_default_field_callback
#define led_protocols_Layer_DEFAULT NULL

#define led_protocols_Animation_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    direction,         1) \
X(a, STATIC,   SINGULAR, UINT32,   duration,          2) \
X(a, CALLBACK, REPEATED, MESSAGE,  layers,            3)
#define led_protocols_Animation_CALLBACK pb_default_field_callback
#define led_protocols_Animation_DEFAULT NULL
#define led_protocols_Animation_layers_MSGTYPE led_protocols_Layer

#define led_protocols_Sequence_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   brightness,        1) \
X(a, CALLBACK, REPEATED, MESSAGE,  animations,        2)
#define led_protocols_Sequence_CALLBACK pb_default_field_callback
#define led_protocols_Sequence_DEFAULT NULL
#define led_protocols_Sequence_animations_MSGTYPE led_protocols_Animation

extern const pb_msgdesc_t led_protocols_Layer_msg;
extern const pb_msgdesc_t led_protocols_Animation_msg;
extern const pb_msgdesc_t led_protocols_Sequence_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define led_protocols_Layer_fields &led_protocols_Layer_msg
#define led_protocols_Animation_fields &led_protocols_Animation_msg
#define led_protocols_Sequence_fields &led_protocols_Sequence_msg

/* Maximum encoded size of messages (where known) */
/* led_protocols_Layer_size depends on runtime parameters */
/* led_protocols_Animation_size depends on runtime parameters */
/* led_protocols_Sequence_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
