/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "src/protocol.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(led_protocols_Layer, led_protocols_Layer, AUTO)


PB_BIND(led_protocols_Animation, led_protocols_Animation, AUTO)


PB_BIND(led_protocols_Sequence, led_protocols_Sequence, AUTO)





