/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Bluetooth: typeof import('./src/components/Bluetooth.vue')['default']
    Serial: typeof import('./src/components/Serial.vue')['default']
  }
}
