/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimationModule: typeof import('./src/components/AnimationModule.vue')['default']
    Bluetooth: typeof import('./src/components/Bluetooth.vue')['default']
    BluetoothMenu: typeof import('./src/components/BluetoothMenu.vue')['default']
    Button: typeof import('primevue/button')['default']
    ColorEffectEditor: typeof import('./src/components/ColorEffectEditor.vue')['default']
    ColorPickerGroup: typeof import('./src/components/ColorPickerGroup.vue')['default']
    MaskEditor: typeof import('./src/components/MaskEditor.vue')['default']
    ModuleSequence: typeof import('./src/components/ModuleSequence.vue')['default']
    PlaySaveButtons: typeof import('./src/components/PlaySaveButtons.vue')['default']
    SaveLocally: typeof import('./src/components/SaveLocally.vue')['default']
    Serial: typeof import('./src/components/Serial.vue')['default']
    SerialConnectButton: typeof import('./src/components/SerialConnectButton.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
